#+TITLE: ITIL
#+AUTHOR: LavenLiu
#+DATE: 2010-08-20
#+EMAIL: ldczz2008@163.com 

#+STARTUP: OVERVIEW
#+TAGS: OFFICE(o) HOME(h) PROJECT(p) CHANGE(c) REPORT(r) MYSELF(m) 
#+TAGS: PROBLEM(P) INTERRUPTTED(i) RESEARCH(R)
#+SEQ_TODO: TODO(t)  STARTED(s) WAITING(W) | DONE(d) CANCELLED(C) DEFERRED(f)
#+COLUMNS: %40ITEM(Details) %TAGS(Context) %7TODO(To Do) %5Effort(Time){:} %6CLOCKSUM{Total}

#+LaTeX_CLASS: book
#+LaTeX_CLASS_OPTIONS: [a4paper,11pt]
#+LaTeX_HEADER: \usepackage[top=2.1cm,bottom=2.1cm,left=2.1cm,right=2.1cm]{geometry}
#+LaTeX_HEADER: \setmainfont[Mapping=tex-text]{Times New Roman}
#+LaTeX_HEADER: \setsansfont[Mapping=tex-text]{Tahoma}
#+LaTeX_HEADER: \setmonofont{Courier New}
#+LaTeX_HEADER: \setCJKmainfont[BoldFont={Adobe Heiti Std},ItalicFont={Adobe Kaiti Std}]{Adobe Song Std}
#+LaTeX_HEADER: \setCJKsansfont{Adobe Heiti Std}
#+LaTeX_HEADER: \setCJKmonofont{Adobe Fangsong Std}
#+LaTeX_HEADER: \punctstyle{hangmobanjiao}
#+LaTeX_HEADER: \usepackage{color,graphicx}
#+LaTeX_HEADER: \usepackage[table]{xcolor}
#+LaTeX_HEADER: \usepackage{colortbl}
#+LaTeX_HEADER: \usepackage{listings}
#+LaTeX_HEADER: \usepackage[bf,small,indentafter,pagestyles]{titlesec}

#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/style2.css" />

#+OPTIONS: ^:nil
#+OPTIONS: tex:t

* ITIL知识
  降低用户期望，提高用户预期。
** ITIL简介
   ITIL即IT基础架构库(Information Technology Infrastructure Library).

   英国商务办公室从20世纪80年代开始开发的一套IT管理方法；

   已成为事实上的行业标准，并以其为中心在全球形成了完整的产业；

   任何单位和个人都可免费使用的“公共框架”；

   实际上是一系列由所谓“最佳实践”(Best Practice)形成的图书。

   ITIL不是什么：
   + 硬件
   + 软件

   ITIL是：
   + 一个可以直接使用的标准
   + 已于2005年12月15日被ISO接受为国际标准 - ISO20000
** ITIL的目标
   1. 将IT管理工作标准化，模式化。减少人为误操作带来的隐患。
   2. 通过服务目录，服务报告，告诉业务部门，我们可以做什么，做了什么。
   3. 通过系列流程，知识库减轻对英雄式工程师的依赖。把经验积累下来。
   4. 通过对流程的管控，减少成本，降低风险，提供客户满意度。 
** IT Service CMM
   1. 初始级(Initial)
	  + 被动响应，没有文档记录，几乎没有过程是经过定义的
	  + 各项目经验无法重用，依赖于个人的努力和英雄主义
   2. 可重复级(Repeatable)
	  + 建立了基本的服务管理过程
	  + 所有项目有默认的规则，但未文档化、系统化
	  + 产品或服务无清晰的目标和策略
   3. 定义级(Defined)
	  + 已将IT服务过程文档化，标准化，并综合成标准服务过程
	  + 根据客户需求调整服务产品或服务战略
	  + 适当的工具和信息报告
   4. 管理级(Managed)
	  + 受监督、测量的IT服务体系
	  + 根据业务战略调整服务体系
   5. 优化级(Optimizing)
	  + 继续改进的IT服务体系
	  + IT与业务指标建立关系
	  + IT与业务协作改进流程
** ITIL V3
   ITIL V3强ITIL理论分成了五个部分：
   + 服务战略(Service Strategy)
   + 服务设计(Service Design)
   + 服务转换(Service Transition)
   + 服务运营(Service Operation)
   + 持续服务改进(Continual Service Improvement)
							
   #+BEGIN_SRC sh
   +-------------+-------------+-------------+------------+-------------+ 	   	  
   | 服务战略    | 服务设计    | 服务转换    | 服务运营   | 持续服务改进|
   +-------------+-------------+-------------+------------+-------------+

   -------------->------------->------------->------------>------------->
   #+END_SRC

*** 服务战略
	从组织能力和战略资产两个角度出发，为组织进行服务战略方面的决策和战
	略设计提供一套结构化的方法。

	服务战略目标：
	+ 我们的业务是什么？
	+ 我们的客户是谁？
	+ 客户重视什么？
	+ 谁依赖我们的服务？
	+ 他们怎样使用我们的服务？
	+ 服务为什么对他们有价值？

	服务战略4P：
	+ 观念(Perspective)：面向其目标客户的业务定位或服务提供方式
	+ 定位(Position)：描述了采纳和中立场的决策
	+ 计划(Plan)：描述了将蓝图转化为现实的手段
	+ 模式(Pattern)：描述了一系列的稳定的决策和行动

	服务战略包括：
	#+BEGIN_SRC sh
    +---------------------+
    |    战略产生      	  |
    +---------------------+
    |    需求管理      	  |
    +---------------------+
    |    服务组合管理  	  |
    +---------------------+
    |    财务管理         |
    +---------------------+
	#+END_SRC

*** 服务设计
	对服务及服务管理流程设计和开发的指导。

	服务设计包括：
	#+BEGIN_SRC sh
    +--------------------------+
    |    供应商管理            |
    +--------------------------+
    |    服务目录管理          |
    +--------------------------+
    |    IT服务持续性管理      |
    +--------------------------+		   					
    |    容量规划              |
    +--------------------------+
    |    可用性管理            |
    +--------------------------+
    |    服务级别管理          |
    +--------------------------+	
	#+END_SRC

	服务设计流程：
	+ 服务目录管理
	+ 服务级别管理 - SLA(Service Level Agreement)服务等级协议。
	+ 容量管理 - Web容量规划
	+ 可用性管理 - 正常运行时间，宕机时间
	+ IT服务持续性管理 - 灾备，恢复计划，影响评估
	+ 信息安全管理
   
*** 服务转换(实施)
	为如何将新的或变更的服务转换到运营过程中，并就相关能力的开发和改进
	提供了深入的指导。

	服务转换(或服务实施)包括：
	#+BEGIN_SRC sh
    +--------------------------+
    |    知识管理  	  	       |
    +--------------------------+
    |    评估  	               |
    +--------------------------+
    |    服务检验与测试        |
    +--------------------------+
    |	 转换规划与支持	       |
    +--------------------------+
    |    发布与部署管理	       |
    +--------------------------+
    |    服务资产与配置管理    |
    +--------------------------+
    |    变更管理              |
    +--------------------------+
	#+END_SRC
*** 服务运营
	服务运营是指在IT服务发布上线之后日常运行维护的阶段。

	服务运营包括：
	#+BEGIN_SRC sh
    +--------------------------+
    |    IT运营管理	  	       |
    +--------------------------+
    |    应用管理              |
    +--------------------------+
    |    技术管理              |
    +--------------------------+
    |	 请求实现  	  	       |
    +--------------------------+
    |    事件管理     	       |
    +--------------------------+
    |    访问管理              |
    +--------------------------+
    |    问题管理              |
    +--------------------------+
    |    事故管理              |
    +--------------------------+
    |    服务台                |
    +--------------------------+	
	#+END_SRC

	流程与职能：
	#+BEGIN_EXAMPLE
	为有效和高效地完成服务支持和服务提供，确保客户和服务提供者的
	利益提供指导方针。

	流程：
	+ 事件管理
	+ 故障管理
	+ 问题管理
	+ 权限管理
	+ 操作管理
	+ 请求实现

	职能：
	+ 服务台
	+ 技术管理
	+ IT运营管理
	+ 应用管理
	#+END_EXAMPLE
**** 故障管理
	 故障管理的目标：
	 #+BEGIN_EXAMPLE
	 故障管理的目标是尽可能快地恢复到正常的服务运营，将故障对业务运营
	 的负面影响减小对最低，并确保达到最好的服务质量和可用性水平。
	 #+END_EXAMPLE
	 
	 综合考虑如下两个方面：
	 + 紧急度(Urgency)
	 + 影响度(Impact)

     影响度：    
	 #+BEGIN_EXAMPLE
         |    | 高 | 中 | 低 |
         |----+----+----+----|
      紧 | 高 |  1 |  2 |  3 |
         |----+----+----+----|
      急 | 中 |  2 |  3 |  4 |
         |----+----+----+----|
      度 | 低 |  3 |  4 |  5 |
	  #+END_EXAMPLE

     | 优先级 | 描述     | 解决时间 |
     |--------+----------+----------|
     |      1 | Critical | 1 hour   |
     |      2 | High     | 8 hour   |
     |      3 | Medium   | 24 hour  |
     |      4 | Low      | 48 hour  |
     |      5 | Planning | Planned  |
	
	 故障管理流程输入：
	 + 故障请求提交
	 + 故障单记录模板
	 + 故障单填写模板
	 + 故障分类规则
	 + 故障优先级确定规则
	 + 故障升级规则
	 + 故障处理时间规则
	 + 故障关闭规则

	 故障管理流程输出：
	 + 故障历史记录
	 + 故障分类汇总统计表
	 + 故障处理用户满意度
*** 持续服务改进
** ITIL V3核心模块
   一个图
** 流程与职能
   RACI模型
** 角色
   + 服务所有者
   + 流程所有者

   流程管理的目标应该是多元化的，流程应该关注：效率、成本、质量、风险、
   稳定性、可持续性、用户体验。
** 一些书籍
   + PMbok
   + ITIL
