#+TITLE: James How To
#+AUTHOR: 刘川
#+DATE: 2015-09-18
#+EMAIL: liuchuanchuan@loukou.com

#+STARTUP: OVERVIEW
#+TAGS: OFFICE(o) HOME(h) PROJECT(p) CHANGE(c) REPORT(r) ZY(y) MYSELF(m) 
#+TAGS: PROBLEM(P) INTERRUPTTED(i) RESEARCH(R)
#+SEQ_TODO: TODO(t)  STARTED(s) WAITING(W) | DONE(d) CANCELLED(C) DEFERRED(f)
#+COLUMNS: %40ITEM(Details) %TAGS(Context) %7TODO(To Do) %5Effort(Time){:} %6CLOCKSUM{Total}

#+LaTeX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [a4paper,11pt]
#+LaTeX_HEADER: \usepackage[top=2.1cm,bottom=2.1cm,left=2.1cm,right=2.1cm]{geometry}
#+LaTeX_HEADER: \usepackage{fontspec}
#+LaTeX_HEADER: \setmainfont[Mapping=tex-text]{Times New Roman}
#+LaTeX_HEADER: \setsansfont[Mapping=tex-text]{Tahoma}
#+LaTeX_HEADER: \setmonofont{Courier New}
#+LaTeX_HEADER: \usepackage{ctex}
#+LaTeX_HEADER: \setCJKmainfont[BoldFont={Adobe Heiti Std},ItalicFont={Adobe Kaiti Std}]{Adobe Song Std}
#+LaTeX_HEADER: \setCJKsansfont{Adobe Heiti Std}
#+LaTeX_HEADER: \setCJKmonofont{Adobe Fangsong Std}
#+LaTeX_HEADER: \punctstyle{hangmobanjiao}
#+LaTeX_HEADER: \usepackage{color,graphicx}
#+LaTeX_HEADER: \usepackage[table]{xcolor}
#+LaTeX_HEADER: \usepackage{colortbl}
#+LaTeX_HEADER: \usepackage{listings}
#+LaTeX_HEADER: \usepackage[bf,small,indentafter,pagestyles]{titlesec}
#+LaTeX_HEADER: \renewcommand{\baselinestretch}{1.38}
#+LaTeX_HEADER: \setlength{\baselineskip}{20pt}

* James安装及配置
** 测试环境
   以下是测试环境，
   |    服务器IP | 主机名     |
   |-------------+------------|
   | 10.10.7.154 | vm-7-154   |
** 安装Java环境
   Java的环境一般情况下已具备，如果没有，请到统一配置管理端进行安装之。
   这里省略安装过程。

   Java安装完毕要设置环境变量，以让与Java相关的应用程序可以使用。
   （JAVA_HOME环境变量的设置是必须的）

   #+BEGIN_SRC bash
   JAVA_HOME=/usr/local/jdk
   CLASS_PATH=$JAVA_HOME/lib:$JAVA_HOME/jre/lib
   PATH=$PATH:$JAVA_HOME/bin
   export JAVA_HOME
   #+END_SRC

   设置完毕，检验一下Java的可用性，
   #+BEGIN_SRC bash
   # java -version
   java version "1.7.0_80-ea"
   Java(TM) SE Runtime Environment (build 1.7.0_80-ea-b03)
   Java HotSpot(TM) 64-Bit Server VM (build 24.80-b07, mixed mode)
   #+END_SRC
   
** 获取James安装包并安装
** 设置环境变量
   #+BEGIN_SRC bash
   # vi /etc/profile
   export PHOENIX_HOME=/usr/local/james-2.3.2

   # . /etc/profile
   #+END_SRC

** 启动James服务
   确认25，110,119端口没有被其他应用程序占用，如占用，杀掉相应的进程，
   确认lsof没有输出
   #+BEGIN_SRC bash
   # lsof -i:25   
   #+END_SRC

   如果25端口被占用，一般是postfix进程在使用，可以关闭postfix进程，并
   让其开机不自动启动即可。
   #+BEGIN_SRC bash
   # service postfix stop
   # chkconfig postfix off
   # lsof -i:110
   # lsof -i:119   
   #+END_SRC

   如果一切正常，首先启动james，启动之后，程序会把james.jar包解开，并
   生成相应的目录及文件

   #+BEGIN_SRC bash
   # chmod +x /usr/local/james-2.3.2/bin/run.sh 
   # chmod +x /usr/local/james-2.3.2/bin/phoenix.sh
   # chmod +x /usr/local/james-2.3.2/bin/sendmail.py
   # /usr/local/james-2.3.2/bin/phoenix.sh start
   Using PHOENIX_HOME:   /usr/local/james-2.3.2
   Using PHOENIX_TMPDIR: /usr/local/james-2.3.2/temp
   Using JAVA_HOME:      /usr/local/jdk1.7.0_80
   Running Phoenix: 

   Phoenix 4.2

   James Mail Server 2.3.2
   Remote Manager Service started plain:4555
   POP3 Service started plain:110
   SMTP Service started plain:25
   NNTP Service started plain:119
   FetchMail Disabled
   #+END_SRC

   已经启动成功，可以查看进程侦听的端口号，
   #+BEGIN_SRC bash
   # netstat -antup
   Active Internet connections (servers and established)
   Proto Recv-Q Send-Q Local Address      Foreign Address      State       PID/Program name   
   tcp        0      0 0.0.0.0:22         0.0.0.0:*            LISTEN      941/sshd            
   tcp        0     52 10.11.1.105:22     192.168.56.1:56627   ESTABLISHED 1072/sshd           
   tcp        0      0 :::4555            :::*                 LISTEN      1525/java           
   tcp        0      0 :::110             :::*                 LISTEN      1525/java           
   tcp        0      0 :::22              :::*                 LISTEN      941/sshd            
   tcp        0      0 :::119             :::*                 LISTEN      1525/java           
   tcp        0      0 :::25              :::*                 LISTEN      1525/java
   #+END_SRC
** 修改James配置
   由于已经启动了James进程，这时已经有了James的配置文件，接下来修改
   james配置文件，配置文件位置在
   /usr/local/james-2.3.2/apps/james/SAR-INF/config.xml

   修改以下几处配置：

   修改postmaster字段：（这里是发送邮件时所使用的域名lk.com）
   #+BEGIN_EXAMPLE
   <postmaster>admin@lk.com</postmaster>
   #+END_EXAMPLE

   修改servername字段：（这里的servername可以随便取名，不能含有下划线）
   #+BEGIN_EXAMPLE
   <servernames autodetect="false" autodetectIP="false">
       <servername>vm7154</servername>
   </servernames>
   #+END_EXAMPLE

   修改dnsserver字段下面的servers字段，（如果要发外网邮件，请添加相应的外网DNS）
   #+BEGIN_EXAMPLE
   <server>127.0.0.1</server>
   <server>202.96.209.133</server>
   #+END_EXAMPLE

   确保pop3server字段与smtpserver字段中的enabled为true，
   #+BEGIN_EXAMPLE
   <pop3server enabled="true">
   <smtpserver enabled="true">
   #+END_EXAMPLE

   添加认证地址，找到authorizedAddresses字段，修改为如下内容，
   #+BEGIN_EXAMPLE
   <authorizedAddresses>127.0.0.0/8,10.10.7.0/24</authorizedAddresses>
   #+END_EXAMPLE

   找到如下内容，
   #+BEGIN_EXAMPLE
   <mailet match="RemoteAddrNotInNetwork=127.0.0.1" class="ToProcessor">
       <processor> relay-denied </processor>
       <notice>550 - Requested action not taken: relaying denied</notice>
   </mailet>
   #+END_EXAMPLE

   并将其注释：
   #+BEGIN_EXAMPLE
   <!--
   <mailet match="RemoteAddrNotInNetwork=127.0.0.1" class="ToProcessor">
       <processor> relay-denied </processor>
       <notice>550 - Requested action not taken: relaying denied</notice>
   </mailet>
   -->
   #+END_EXAMPLE
** 增加James邮件用户
   当一切就绪，就增设几个用户来进行邮件的发送吧。
   | 命令                               | 说明                                 |
   |------------------------------------+--------------------------------------|
   | help                               | 显示帮助                             |
   | listusers                          | 列出目前存在的账户                   |
   | countusers                         | 显示目前存在的账户的数量             |
   | adduser [用户名] [密码]            | 添加新用户                           |
   | verify [用户名]                    | 验证特定用户是否存在                 |
   | deluser [用户名]                   | 删除已存在用户                       |
   | setpassword [用户名] [密码]        | 设置某一用户的密码                   |
   | setalias [别名] [用户名]           | 从本地将[别名]的所有邮件转寄[用户名] |
   | unsetalias [别名]                  | 取消setalias设置                     |
   | setforwarding [用户名] [email地址] | 将[用户名]的邮件转寄指定[email地址]  |
   | unsetforwarding [用户名]           | 取消setforwarding设置                |
   | user [资源]                        | 变为另一用户的资源                   |
   | shutdown                           | 停止当前James邮件服务的JVM程序       |
   | quit                               | 断开telnet连接                       |

   给个例子看看：
   #+BEGIN_SRC bash
   # telnet 127.0.0.1 4555
   Trying 127.0.0.1...
   Connected to 127.0.0.1.
   Escape character is '^]'.
   JAMES Remote Administration Tool 2.3.2
   Please enter your login and password
   Login id:
   root  # 输入用户名root
   Password:
   root  # 输入密码
   Welcome root. HELP for a list of commands
   listusers # 查看已有的用户
   Existing accounts 2
   user: applogscan
   user: monitor
   adduser liuchuan 123456 # 增加liuchuan这个用户
   User liuchuan added
   quit # 退出登录
   Bye
   Connection closed by foreign host.
   #+END_SRC
** iptables放行James服务端相应端口
   在开启了iptables环境的机器上搭建james邮件服务，需要设置iptables规则，
   设置如下：编辑/etc/sysconfig/iptables文件，添加如下几行（在REJECT字
   样的上面添加）：
   
   #+BEGIN_EXAMPLE
   -A INPUT -m state --state NEW -m tcp -p tcp --dport 110 -j ACCEPT
   -A INPUT -m state --state NEW -m tcp -p tcp --dport 25 -j ACCEPT
   -A INPUT -m state --state NEW -m tcp -p tcp --dport 4555 -j ACCEPT
   -A INPUT -m state --state NEW -m tcp -p tcp --dport 119 -j ACCEPT
   #+END_EXAMPLE

   完毕之后，重启iptables即可。
   #+BEGIN_SRC bash
   # service iptables restart
   #+END_SRC
* 使用sendEmail邮件客户端发送邮件
  sendEmail是用Perl写的一个命令行发送邮件脚本，很赞的一个工具。首先下
  载到本地进行使用即可，

  下载之，
  #+BEGIN_SRC bash
  # wget http://caspian.dotconf.net/menu/Software/SendEmail/sendEmail-v1.56.tar.gz
  #+END_SRC

  解压并放置到PATH路径中，
  #+BEGIN_SRC bash
  # tar -xf sendEmail-v1.56.tar.gz
  # cd sendEmail-v1.56
  # cp sendEmail /usr/local/bin
  # chmod +x /usr/local/bin/sendEmail
  #+END_SRC
** 常用选项
   接下来，简单介绍一下sendEmail的一些基本选项，
   #+BEGIN_EXAMPLE
   选项说明：
   -a  表示此邮件有附件
   -f  表示发送者的邮箱
   -t  表示接收者的邮箱，可以有多个接收者，多个邮件地址用分号隔开
   
   -cc 表示抄送给谁，多个地址用空格分开
   -s  表示SMTP服务器的域名或IP
   -u  表示邮件的主题
   -xu 表示SMTP验证的用户名
   -xp 表示SMTP验证的密码（注意：有特殊字符的不能被识别）
   -m  表示邮件的内容，如果不带m参数，就会提示你自行输入，使用Ctrl-D结束
   #+END_EXAMPLE
** 一个发送邮件的例子
   #+BEGIN_SRC bash
   # sendEmail -f monitor@lk.com -t zhangyi@loukou.com -s 10.10.7.154 -xu monitor -xp moni1234 -u "Email Title" -m "This is a test."
   #+END_SRC
   注意，-f选项后面的发件人地址可以随意填写，不过要符合RFC 1034或RFC
   1035的规则。如果@后面域名只有lk，则收件人在收到邮件后，他的发件人将
   显示“monitor@lk.NULL.NULL”这种样式。
